### ISSUE TITLE
how to interface

### ISSUE THREAD

**Issue by grenzionky** [progwolff/moc-mpris#3]
does this work with playerctl? cuz i cant get it to work… i tried compiling it myself, or from the aur, but it doesnt seem to do anything. i set up the systemd service as the instructions say and i got the green light from `systemctl status`, so idk whats wrong. i dont see `moc` listed as a player in `playerctl -l`

**Comment by progwolff** [comment]
Works fine for me...
What is the output of /usr/lib/moc-mpris/moc_mpris.sh?

**Comment by grenzionky** [comment]
```bash
~ > /usr/lib/moc-mpris/moc_mpris.sh
['-i']
None@None
~ > /usr/lib/moc-mpris/moc_mpris.sh -i
['-i']
-i@-i
```

**Comment by progwolff** [comment]
This indicates that there is no instance of moc playing music.

**Comment by grenzionky** [comment]
i see
turning on a song in moc, and then running /usr/lib/moc-mpris/moc_mpris.sh does make it work

is there a way to make it automatically run when a song starts? or keep it running in the background while moc is running? like by doing something like `alias mocp="mocp & /usr/lib/moc-mpris/moc_mpris.sh"`?

also, the moc_mpris service makes no difference whether its running or not. it works just fine without it

**Comment by progwolff** [comment]
If you want to run the script in background to auto-detect moc, just enable the service. It does exactly this: restarting the script until moc is found.

**Comment by xxxserxxx** [comment]
I'll just note that this means the project has a hard dependency on systemd.
